[package]
name = "discord_game_sdk_mock"
version = "0.1.0"
authors = ["ldesgoui <ldesgoui@gmail.com>"]
edition = "2018"

[lib]
name = "discord_game_sdk"
crate-type = ["dylib"]

[dependencies]
pretty_env_logger = "0.3.0"
log = "0.4.6"
memoffset = "0.3.0"
scopeguard = "1.0.0"

[dependencies.discord_game_sdk_sys]
path = "../sys"
version = "0.1.0"
features = ["no_linking"]
