[package]
name = "discord_game_sdk"
version = "0.1.0"
authors = ["ldesgoui <ldesgoui@gmail.com>"]
edition = "2018"
description = "Safe wrapper for the Discord Game SDK"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ldesgoui/discord_game_sdk"
keywords = ["discord", "sdk", "gamedev"]
categories = ["api-bindings", "game-engines"]

[features]
mock = ["discord_game_sdk_sys/mock", "discord_game_sdk_mock"]

[dependencies]
chrono = { version = "0.4.6", default-features = false }
crossbeam-channel = { version = "0.3.8", default-features = false }
derive_more = { version = "0.14.0", default-features = false }
err-derive = { version = "0.1.5", default-features = false }
log = { version = "0.4.6", default-features = false }
discord_game_sdk_sys = { version = "0.1.0", path = "./sys" }
discord_game_sdk_mock = { version = "0.1.0", path = "./mock", optional = true }

[dev-dependencies]
pretty_env_logger = { version = "0.3.0" }

[workspace]
members = ["sys", "mock"]
