[package]
name = "discord_game_sdk"
version = "0.1.0"
authors = ["ldesgoui <ldesgoui@gmail.com>"]
edition = "2018"
description = "Safe wrapper for the Discord Game SDK"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ldesgoui/discord_game_sdk"
keywords = ["discord", "sdk", "gamedev"]
categories = ["api-bindings", "game-engines"]

[features]
mock = ["discord_game_sdk_sys/mock", "discord_game_sdk_mock"]

[dependencies]
chrono = "0.4.6"
crossbeam-channel = "0.3.8"
derive_more = "0.14.0"
err-derive = "0.1.5"
log = "0.4.6"
scopeguard = "1.0.0"

[dependencies.discord_game_sdk_sys]
version = "0.1.0"
path = "./sys"

[dependencies.discord_game_sdk_mock]
version = "0.1.0"
path = "./mock"
optional = true

[dev-dependencies]
pretty_env_logger = "0.3.0"

[workspace]
members = ["sys", "mock"]
