[workspace]
members = ["sys", "mock"]

[package]
name = "discord_game_sdk"
version = "0.1.0"
authors = ["ldesgoui <ldesgoui@gmail.com>"]
edition = "2018"
description = "Rust bindings to the Discord Game SDK"
license = "MIT/Apache 2.0"

[dependencies]
log = "0.4.6"

[features]
default = ["using_mock"]
using_mock = ["discord_game_sdk_sys/using_mock"]
no_linking = ["discord_game_sdk_sys/no_linking"]

[dependencies.discord_game_sdk_sys]
path = "sys"
version = "0.1.0"

[dev-dependencies]
pretty_env_logger = "0.3.0"
