[package]
name = "discord_game_sdk"
version = "0.1.0"
authors = ["ldesgoui <ldesgoui@gmail.com>"]
edition = "2018"
description = "Safe wrapper for the Discord Game SDK"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ldesgoui/discord_game_sdk"
keywords = [ "discord", "sdk", "gamedev" ]
categories = [ "api-bindings", "game-engines" ]

[features]
no_linking = ["discord_game_sdk_sys/no_linking"]

[dependencies]
chrono = "0.4.6"
err-derive = "0.1.5"
log = "0.4.6"
shrev = "1.0.1"

[dependencies.discord_game_sdk_sys]
version = "0.1.0"
path = "./sys"

[dev-dependencies]
pretty_env_logger = "0.3.0"

[workspace]
members = ["sys", "mock"]
